# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='_person_contacts_+', to='user_section.Person'),
        ),
    ]
