# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_section', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='observerResponsable',
            new_name='observerResponsible',
        ),
    ]
