# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-10 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_section', '0004_auto_20170510_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='observer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='user_section.Observer'),
        ),
    ]
