# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program_section', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='active_events',
            new_name='activeEvents',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='passive_events',
            new_name='passiveEvents',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='update_date',
            new_name='updateDate',
        ),
    ]
