# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-25 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
