# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-25 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_section', '0002_auto_20170925_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
