# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_section', '0003_auto_20170925_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='ends',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='starts',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='updateDate',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
