# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventTriger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE_TIME', models.CharField(default='time', max_length=50)),
                ('TYPE_MANUAL', models.CharField(default='manual', max_length=50)),
                ('TYPE_CONTEXTUAL', models.CharField(default='contextual', max_length=50)),
                ('trigger_type', models.CharField(max_length=100)),
                ('trigger_condition', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
            ],
        ),
    ]
