# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtrigger',
            name='triggerType',
            field=models.CharField(default='time', max_length=10),
        ),
    ]
