# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_section', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventTriger',
            new_name='EventTrigger',
        ),
    ]
