# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-10 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_section', '0002_auto_20170508_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtrigger',
            name='TYPE_CONTEXTUAL',
        ),
        migrations.RemoveField(
            model_name='eventtrigger',
            name='TYPE_MANUAL',
        ),
        migrations.RemoveField(
            model_name='eventtrigger',
            name='TYPE_TIME',
        ),
        migrations.AlterField(
            model_name='eventtrigger',
            name='priority',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='eventtrigger',
            name='trigger_condition',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eventtrigger',
            name='trigger_type',
            field=models.CharField(choices=[('T', 'time'), ('M', 'manual'), ('C', 'contextual')], default='T', max_length=1),
        ),
    ]
