# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_section', '0003_auto_20170510_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtrigger',
            old_name='trigger_condition',
            new_name='triggerCondition',
        ),
        migrations.RenameField(
            model_name='eventtrigger',
            old_name='trigger_type',
            new_name='triggerType',
        ),
    ]
