# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intervation_section', '0001_initial'),
        ('sensor_section', '0001_initial'),
        ('trigger_section', '0001_initial'),
        ('result_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('group', models.CharField(max_length=100)),
                ('type', models.CharField(default='active', max_length=50)),
                ('emptyInterventions', models.ManyToManyField(blank=True, to='intervation_section.EmptyIntervention')),
                ('mediaInterventions', models.ManyToManyField(blank=True, to='intervation_section.MediaIntervention')),
                ('mediaResults', models.ManyToManyField(blank=True, to='result_section.MediaResult')),
                ('questionInterventions', models.ManyToManyField(blank=True, to='intervation_section.QuestionIntervention')),
                ('questionResults', models.ManyToManyField(blank=True, to='result_section.QuestionResult')),
                ('sensorResults', models.ManyToManyField(blank=True, to='result_section.SensorResult')),
                ('sensors', models.ManyToManyField(to='sensor_section.Sensor')),
                ('taskInterventions', models.ManyToManyField(blank=True, to='intervation_section.TaskIntervention')),
                ('taskResults', models.ManyToManyField(blank=True, to='result_section.TaskResult')),
                ('triggers', models.ManyToManyField(to='trigger_section.EventTrigger')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PassiveEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('group', models.CharField(max_length=100)),
                ('type', models.CharField(default='passive', max_length=50)),
                ('sensors', models.ManyToManyField(to='sensor_section.Sensor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
