# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='group',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
