# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('result_section', '0002_auto_20171003_1319'),
        ('event_section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeevent',
            name='mediaResults',
        ),
        migrations.RemoveField(
            model_name='activeevent',
            name='questionResults',
        ),
        migrations.RemoveField(
            model_name='activeevent',
            name='sensorResults',
        ),
        migrations.RemoveField(
            model_name='activeevent',
            name='taskResults',
        ),
        migrations.AddField(
            model_name='activeevent',
            name='results',
            field=models.ManyToManyField(blank=True, to='result_section.Result'),
        ),
    ]
