# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-04 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_section', '0002_auto_20171004_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='group',
        ),
    ]
