# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_section', '0002_remove_passiveevent_triggers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeevent',
            old_name='empty_interventions',
            new_name='emptyInterventions',
        ),
        migrations.RenameField(
            model_name='activeevent',
            old_name='media_interventions',
            new_name='mediaInterventions',
        ),
        migrations.RenameField(
            model_name='activeevent',
            old_name='media_results',
            new_name='mediaResults',
        ),
        migrations.RenameField(
            model_name='activeevent',
            old_name='question_interventions',
            new_name='questionInterventions',
        ),
        migrations.RenameField(
            model_name='activeevent',
            old_name='question_results',
            new_name='questionResults',
        ),
        migrations.RenameField(
            model_name='activeevent',
            old_name='sensor_results',
            new_name='sensorResults',
        ),
        migrations.RenameField(
            model_name='activeevent',
            old_name='task_interventions',
            new_name='taskInterventions',
        ),
        migrations.RenameField(
            model_name='activeevent',
            old_name='task_results',
            new_name='taskResults',
        ),
    ]
