# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-25 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervation_section', '0003_auto_20170925_1434'),
        ('event_section', '0003_auto_20170925_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeevent',
            name='emptyInterventions',
        ),
        migrations.RemoveField(
            model_name='activeevent',
            name='mediaInterventions',
        ),
        migrations.RemoveField(
            model_name='activeevent',
            name='questionInterventions',
        ),
        migrations.RemoveField(
            model_name='activeevent',
            name='taskInterventions',
        ),
        migrations.AddField(
            model_name='activeevent',
            name='interventions',
            field=models.ManyToManyField(blank=True, to='intervation_section.Intervention'),
        ),
    ]
