# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_section', '0004_auto_20170925_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeevent',
            name='type',
        ),
        migrations.RemoveField(
            model_name='passiveevent',
            name='type',
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
