# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-22 05:25
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intervention_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskintervention',
            name='parameters',
            field=annoying.fields.JSONField(blank=True, null=True),
        ),
    ]
