# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SENSOR_TYPE_INTERVAL', models.IntegerField(default=0)),
                ('SENSOR_TYPE_TASK', models.IntegerField(default=1)),
                ('SENSOR_ACTIVITY', models.CharField(default='activity', max_length=50)),
                ('SENSOR_ACCELEROMETER', models.CharField(default='accelerometer', max_length=50)),
                ('SENSOR_CAMERA', models.CharField(default='camera', max_length=50)),
                ('SENSOR_LIGHT', models.CharField(default='light', max_length=50)),
                ('SENSOR_MICROPHONE', models.CharField(default='microphone', max_length=50)),
                ('sensor_type', models.IntegerField()),
                ('sensor', models.CharField(max_length=100)),
            ],
        ),
    ]
