# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_section', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='sensor_type',
            new_name='sensorType',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='SENSOR_ACCELEROMETER',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='SENSOR_ACTIVITY',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='SENSOR_CAMERA',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='SENSOR_LIGHT',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='SENSOR_MICROPHONE',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor',
            field=models.CharField(choices=[('ACT', 'activity'), ('ACC', 'accelerometer'), ('CAM', 'camera'), ('LIG', 'light'), ('MIC', 'microphone')], default='activity', max_length=3),
        ),
    ]
