# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARRAY_option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ComplexCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=100)),
                ('next', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=100)),
                ('orderPosition', models.IntegerField()),
                ('first', models.BooleanField(default=False)),
                ('next', models.IntegerField()),
                ('obligatory', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MAP_conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=300)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MediaPresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('I', 'imagem'), ('A', 'audio'), ('V', 'video')], default='I', max_length=1)),
                ('mediaUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='EmptyIntervention',
            fields=[
                ('intervention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='intervation_section.Intervention')),
                ('type', models.CharField(default='empty', max_length=10)),
            ],
            bases=('intervation_section.intervention',),
        ),
        migrations.CreateModel(
            name='MediaIntervention',
            fields=[
                ('intervention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='intervation_section.Intervention')),
                ('type', models.CharField(default='media', max_length=10)),
                ('mediaType', models.CharField(choices=[('I', 'imagem'), ('A', 'audio'), ('V', 'video')], default='I', max_length=1)),
            ],
            bases=('intervation_section.intervention',),
        ),
        migrations.CreateModel(
            name='QuestionIntervention',
            fields=[
                ('intervention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='intervation_section.Intervention')),
                ('type', models.CharField(default='question', max_length=10)),
                ('questionType', models.IntegerField(choices=[(0, 'open_text'), (1, 'radio'), (2, 'checkbox'), (3, 'likert'), (4, 'semantic_differential')], default=0)),
                ('complexConditions', models.ManyToManyField(to='intervation_section.ComplexCondition')),
            ],
            bases=('intervation_section.intervention',),
        ),
        migrations.CreateModel(
            name='TaskIntervention',
            fields=[
                ('intervention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='intervation_section.Intervention')),
                ('type', models.CharField(default='task', max_length=10)),
                ('appPackage', models.CharField(max_length=50)),
            ],
            bases=('intervation_section.intervention',),
        ),
        migrations.AddField(
            model_name='intervention',
            name='medias',
            field=models.ManyToManyField(to='intervation_section.MediaPresentation'),
        ),
        migrations.AddField(
            model_name='map_conditions',
            name='questionIntervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='intervation_section.QuestionIntervention'),
        ),
        migrations.AddField(
            model_name='array_option',
            name='questionIntervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='intervation_section.QuestionIntervention'),
        ),
    ]
