# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARRAY_option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ComplexCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=100)),
                ('next', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmptyIntervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=100)),
                ('order_position', models.IntegerField()),
                ('first', models.BooleanField(default=False)),
                ('next', models.IntegerField()),
                ('obligatory', models.BooleanField(default=False)),
                ('type', models.CharField(default='empty', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MAP_conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=300)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MediaIntervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=100)),
                ('order_position', models.IntegerField()),
                ('first', models.BooleanField(default=False)),
                ('next', models.IntegerField()),
                ('obligatory', models.BooleanField(default=False)),
                ('type', models.CharField(default='media', max_length=10)),
                ('media_type', models.CharField(choices=[('I', 'imagem'), ('A', 'audio'), ('V', 'video')], default='I', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaPresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('I', 'imagem'), ('A', 'audio'), ('V', 'video')], default='I', max_length=1)),
                ('media_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionIntervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=100)),
                ('order_position', models.IntegerField()),
                ('first', models.BooleanField(default=False)),
                ('next', models.IntegerField()),
                ('obligatory', models.BooleanField(default=False)),
                ('type', models.CharField(default='media', max_length=10)),
                ('question_type', models.IntegerField(choices=[(0, 'open_text'), (1, 'radio'), (2, 'checkbox'), (3, 'likert'), (4, 'semantic_differential')], default=0)),
                ('complexConditions', models.ManyToManyField(to='intervation_section.ComplexCondition')),
                ('medias', models.ManyToManyField(to='intervation_section.MediaPresentation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskIntervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=100)),
                ('order_position', models.IntegerField()),
                ('first', models.BooleanField(default=False)),
                ('next', models.IntegerField()),
                ('obligatory', models.BooleanField(default=False)),
                ('type', models.CharField(default='task', max_length=10)),
                ('app_package', models.CharField(max_length=50)),
                ('medias', models.ManyToManyField(to='intervation_section.MediaPresentation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mediaintervention',
            name='medias',
            field=models.ManyToManyField(to='intervation_section.MediaPresentation'),
        ),
        migrations.AddField(
            model_name='map_conditions',
            name='questionIntervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervation_section.QuestionIntervention'),
        ),
        migrations.AddField(
            model_name='emptyintervention',
            name='medias',
            field=models.ManyToManyField(to='intervation_section.MediaPresentation'),
        ),
        migrations.AddField(
            model_name='array_option',
            name='questionIntervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervation_section.QuestionIntervention'),
        ),
    ]
