# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-25 13:48
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('intervation_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionintervention',
            name='conditions',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionintervention',
            name='options',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
