# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-13 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervation_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='statement',
            field=models.CharField(max_length=800),
        ),
    ]
