# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intervation_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='array_option',
            name='questionIntervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='intervation_section.QuestionIntervention'),
        ),
        migrations.AlterField(
            model_name='map_conditions',
            name='questionIntervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='intervation_section.QuestionIntervention'),
        ),
    ]
