# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-25 14:34
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intervation_section', '0002_auto_20170925_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionintervention',
            name='conditions',
            field=annoying.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionintervention',
            name='options',
            field=annoying.fields.JSONField(blank=True, null=True),
        ),
    ]
