# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervation_section', '0002_auto_20170511_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionintervention',
            name='type',
            field=models.CharField(default='question', max_length=10),
        ),
    ]
