# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervation_section', '0003_auto_20170925_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaintervention',
            name='mediaType',
            field=models.CharField(default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='mediapresentation',
            name='type',
            field=models.CharField(default='image', max_length=10),
        ),
    ]
