# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intervation_section', '0003_auto_20170511_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emptyintervention',
            old_name='order_position',
            new_name='orderPosition',
        ),
        migrations.RenameField(
            model_name='mediaintervention',
            old_name='media_type',
            new_name='mediaType',
        ),
        migrations.RenameField(
            model_name='mediaintervention',
            old_name='order_position',
            new_name='orderPosition',
        ),
        migrations.RenameField(
            model_name='mediapresentation',
            old_name='media_url',
            new_name='mediaUrl',
        ),
        migrations.RenameField(
            model_name='questionintervention',
            old_name='order_position',
            new_name='orderPosition',
        ),
        migrations.RenameField(
            model_name='questionintervention',
            old_name='question_type',
            new_name='questionType',
        ),
        migrations.RenameField(
            model_name='taskintervention',
            old_name='app_package',
            new_name='appPackage',
        ),
        migrations.RenameField(
            model_name='taskintervention',
            old_name='order_position',
            new_name='orderPosition',
        ),
    ]
