# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervation_section', '0004_auto_20170928_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emptyintervention',
            name='type',
        ),
        migrations.RemoveField(
            model_name='mediaintervention',
            name='type',
        ),
        migrations.RemoveField(
            model_name='questionintervention',
            name='type',
        ),
        migrations.RemoveField(
            model_name='taskintervention',
            name='type',
        ),
        migrations.AddField(
            model_name='intervention',
            name='type',
            field=models.CharField(default='general', max_length=10),
        ),
    ]
