# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intervation_section', '0005_auto_20170928_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emptyintervention',
            options={'verbose_name': 'empty'},
        ),
    ]
