# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intervation_section', '0006_auto_20170928_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emptyintervention',
            options={},
        ),
    ]
