# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervation_section', '0007_auto_20170928_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='type',
            field=models.CharField(default='empty', max_length=10),
        ),
    ]
